import re
from urllib.parse import urlparse, unquote

URGENT_SUBJECT_KEYWORDS = [
    "urgent", "action required", "verify", "confirm", "reset", "account", "secure", "payment", "invoice", "suspended"
]

PHISHING_BODY_KEYWORDS = [
    "click", "login", "verify", "account", "password", "credentials", "update", "secure", "reset", "urgent", "wire transfer", "bank"
]

SUSPICIOUS_SENDERS = [
    "noreply", "support", "service", "security", "admin", "help", "alerts"
]

SHORTENER_DOMAINS = {
    "bit.ly", "tinyurl.com", "goo.gl", "t.co", "ow.ly", "buff.ly", "adf.ly", "short.ly", "is.gd", "cutt.ly"
}

FREE_EMAIL_DOMAINS = {
    "gmail.com", "yahoo.com", "hotmail.com", "outlook.com", "protonmail.com", "icloud.com", "aol.com", "mail.com"
}


def extract_urls(text):
    return re.findall(r"https?://[\w\-\.\/%&=?#]+", text or "")


def email_sender_domain(sender):
    match = re.search(r"@([\w\-\.]+)", sender or "")
    return match.group(1).lower() if match else ""


def check_shortened_links(links):
    return any(urlparse(url).netloc.lower() in SHORTENER_DOMAINS for url in links)


def check_email(sender, subject, body):
    sender = sender or ""
    subject = subject or ""
    body = body or ""

    features = {}
    sender_domain = email_sender_domain(sender)
    links = extract_urls(body)
    shortened_urls = check_shortened_links(links)
    linked_domains = [urlparse(link).netloc.lower().split("@")[-1].split(":")[0] for link in links]

    features["sender_domain"] = sender_domain
    features["subject_urgent"] = any(keyword in subject.lower() for keyword in URGENT_SUBJECT_KEYWORDS)
    features["body_phishing_words"] = any(keyword in body.lower() for keyword in PHISHING_BODY_KEYWORDS)
    features["suspicious_sender_name"] = any(keyword in sender.lower() for keyword in SUSPICIOUS_SENDERS)
    features["sender_free_domain"] = sender_domain in FREE_EMAIL_DOMAINS
    features["contains_links"] = len(links) > 0
    features["shortened_links"] = shortened_urls
    features["body_length"] = len(body.strip())
    features["has_html_tags"] = bool(re.search(r"<\s*\w+.*?>", body))
    features["sender_domain_mismatch"] = bool(sender_domain and linked_domains and not any(domain == sender_domain for domain in linked_domains))
    features["subject_all_caps"] = subject.strip() and subject.strip().upper() == subject.strip() and len(subject.strip()) > 10
    features["attachment_language"] = bool(re.search(r"attachment|file|invoice|document|pdf", body.lower()))
    features["suspicious_sender_format"] = bool(re.search(r"\d{3,}|[-_.]{2,}", sender.split("@")[0]))
    features["urgent_language"] = features["subject_urgent"] or features["body_phishing_words"]

    result = calculate_email_risk(features, sender, subject, links)
    result["features"] = features
    return result


def calculate_email_risk(features, sender, subject, links):
    score = 0
    reasons = []
    recommendations = []
    fixes = []

    if features.get("subject_urgent"):
        score += 15
        reasons.append("Urgent or pressure-based subject line")
        recommendations.append("Treat messages that demand immediate action with caution.")

    if features.get("body_phishing_words"):
        score += 15
        reasons.append("Suspicious keywords found in the email body")
        recommendations.append("Watch for words that commonly appear in phishing content.")

    if features.get("contains_links"):
        score += 10
        reasons.append("Includes links in the email")
        recommendations.append("Inspect each link before clicking and use the scanner if you are unsure.")

    if features.get("shortened_links"):
        score += 20
        reasons.append("Shortened links detected")
        recommendations.append("Expand shortened links before following them.")

    if features.get("suspicious_sender_name"):
        score += 10
        reasons.append("Suspicious sender address pattern")
        recommendations.append("Check whether the sender address looks unusual or autogenerated.")

    if features.get("sender_free_domain") and features.get("contains_links"):
        score += 10
        reasons.append("Free email service used for a message that includes links")
        recommendations.append("Official services usually send important notices from corporate domains.")

    if features.get("sender_domain_mismatch"):
        score += 15
        reasons.append("Sender domain does not match linked domains")
        recommendations.append("If links go to a different domain than the sender, treat the message as suspicious.")

    if features.get("subject_all_caps"):
        score += 10
        reasons.append("Subject line is written in all capital letters")
        recommendations.append("All-caps subjects are a common tactic to create urgency.")

    if features.get("attachment_language"):
        score += 10
        reasons.append("Language suggests an attachment or invoice")
        recommendations.append("Be careful when attachments are requested unexpectedly.")

    if features.get("suspicious_sender_format"):
        score += 10
        reasons.append("Sender address uses a suspicious format")
        recommendations.append("Look for random characters or unusual punctuation in the sender address.")

    if features.get("body_length") < 50:
        score += 5
        reasons.append("Very short email body")
        recommendations.append("Short messages with urgent requests can be suspicious.")
        fixes.append("Ask for more context before responding to short, urgent emails.")

    if features.get("has_html_tags"):
        score += 5
        reasons.append("HTML content detected")
        recommendations.append("Email HTML can hide dangerous links; use plain text mode if possible.")
        fixes.append("View the email in plain-text mode to inspect hidden link destinations.")

    if not reasons:
        recommendations.append("This email looks low risk, but verify the sender and avoid clicking links unless expected.")
        fixes.append("If unsure, do not reply and confirm the request through a separate channel.")

    if score >= 50:
        verdict = "PHISHING"
    elif score >= 25:
        verdict = "SUSPICIOUS"
    else:
        verdict = "LEGIT"

    details = {
        "sender": sender,
        "subject": subject,
        "links": links,
        "sender_domain": features.get("sender_domain"),
        "shortened_links": features.get("shortened_links"),
        "has_html_tags": features.get("has_html_tags"),
        "sender_domain_mismatch": features.get("sender_domain_mismatch"),
        "subject_all_caps": features.get("subject_all_caps"),
        "attachment_language": features.get("attachment_language"),
        "suspicious_sender_format": features.get("suspicious_sender_format"),
        "contains_links": features.get("contains_links"),
        "sender_free_domain": features.get("sender_free_domain"),
        "urgent_language": features.get("urgent_language")
    }

    return {
        "score": score,
        "verdict": verdict,
        "reasons": reasons,
        "recommendations": recommendations,
        "fixes": fixes,
        "details": details
    }
